-- ============================================================
-- 01_setup.sql — Warehouse, Database, Schemas
-- ============================================================

CREATE WAREHOUSE IF NOT EXISTS OEE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS OEE_CC;

CREATE SCHEMA IF NOT EXISTS OEE_CC.RAW;
CREATE SCHEMA IF NOT EXISTS OEE_CC.CONVERGED;
CREATE SCHEMA IF NOT EXISTS OEE_CC.ML;
CREATE SCHEMA IF NOT EXISTS OEE_CC.OPS;
CREATE SCHEMA IF NOT EXISTS OEE_CC.APP;

USE WAREHOUSE OEE_WH;
USE DATABASE OEE_CC;
USE SCHEMA RAW;
